# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'capybara'
gem 'pg'
gem 'rspec'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-flash'
gem 'simplecov'
gem 'simplecov-console'

group :development, :test do
  gem 'rubocop', '1.20'
end
